services:
  # 1. Banco de Dados
  db:
    image: mysql:8.0
    container_name: sistema_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3307:3306" # Porta externa 3307 para não conflitar com seu XAMPP/Laragon
    volumes:
      - db_data:/var/lib/mysql

  # 2. Backend (PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sistema_backend
    restart: always
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  # 3. Servidor Web do Backend (Nginx)
  backend-server:
    image: nginx:alpine
    container_name: sistema_backend_server
    restart: always
    ports:
      - "8080:80" # Backend acessível na porta 8080
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  # 4. Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sistema_frontend
    restart: always
    ports:
      - "3000:80" # Frontend acessível na porta 3000
    depends_on:
      - backend-server

volumes:
  db_data: